import React, { useState, useEffect } from 'react';
import confetti from 'canvas-confetti';
import { useAuth } from '../../context/AuthContext';
import { useToast } from '../../context/ToastContext';
import { apiRequest } from '../../lib/api';
import { Ticket, Sparkles, Gift, CheckCircle2, History } from 'lucide-react';

interface UserRedemption {
  id: string;
  promoCode: string;
  rewardAmount: number;
  redeemedAt: string;
}

export const PromoView: React.FC = () => {
  const { user, refreshProfile } = useAuth();
  const { success, error } = useToast();

  const [code, setCode] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [myRedemptions, setMyRedemptions] = useState<UserRedemption[]>([]);
  const [loadingHistory, setLoadingHistory] = useState(true);

  const fetchMyHistory = async () => {
    if (!user) {
      setLoadingHistory(false);
      return;
    }
    try {
      const data = await apiRequest<{ redemptions?: UserRedemption[] }>('/api/promo/my');
      setMyRedemptions(data.redemptions || []);
    } catch (err: any) {
      if (err?.message?.includes('Session expired') || err?.message?.includes('Authentication required')) {
        setMyRedemptions([]);
      } else {
        console.warn('Unable to load redemption history:', err?.message || err);
      }
    } finally {
      setLoadingHistory(false);
    }
  };

  useEffect(() => {
    if (user) {
      fetchMyHistory();
    } else {
      setLoadingHistory(false);
    }
  }, [user]);

  const handleRedeem = async (e: React.FormEvent) => {
    e.preventDefault();
    const targetCode = code.trim().toUpperCase();

    if (!targetCode) {
      error('Please enter the promotional code.');
      return;
    }

    setSubmitting(true);
    try {
      const res = await apiRequest<{ message: string; rewardAmount: number }>('/api/promo/redeem', {
        method: 'POST',
        body: JSON.stringify({ code: targetCode }),
      });

      confetti({
        particleCount: 100,
        spread: 70,
        origin: { y: 0.6 },
      });

      success(res.message || `Code redeemed! +$${res.rewardAmount.toFixed(2)} credited to your wallet.`);
      setCode('');
      await refreshProfile();
      await fetchMyHistory();
    } catch (err: any) {
      error(err.message || 'Invalid or expired promo code.');
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="space-y-6 max-w-7xl mx-auto">
      {/* Header */}
      <div>
        <h1 className="text-2xl font-extrabold text-white tracking-tight flex items-center gap-2.5">
          <Ticket className="w-6 h-6 text-purple-400" />
          Promo Code Redemption
        </h1>
        <p className="text-xs sm:text-sm text-slate-400 mt-1">
          Enter official promotional vouchers generated by administration to receive instant balance bonuses.
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left: Input box (Confidential Redemption Only) */}
        <div className="lg:col-span-6 space-y-6">
          <div className="bg-[#0e1628]/90 border border-slate-800 rounded-3xl p-6 sm:p-8 relative overflow-hidden">
            <div className="absolute -top-16 -right-16 w-48 h-48 bg-purple-500/10 rounded-full blur-3xl pointer-events-none" />

            <div className="w-12 h-12 rounded-2xl bg-purple-500/15 text-purple-400 flex items-center justify-center mb-4">
              <Gift className="w-6 h-6" />
            </div>

            <h2 className="text-xl font-bold text-white mb-2">Redeem Secret Promo Voucher</h2>
            <p className="text-xs text-slate-400 mb-6 leading-relaxed">
              Promo codes are distributed exclusively through administrator announcements, special events, and official channels. Enter your code below to instantly claim your reward.
            </p>

            <form onSubmit={handleRedeem} className="space-y-4">
              <div>
                <label className="block text-xs font-semibold text-slate-300 mb-1.5">
                  Enter Promo Code
                </label>
                <div className="relative">
                  <input
                    type="text"
                    placeholder="Enter Admin Issued Code"
                    value={code}
                    onChange={(e) => setCode(e.target.value.toUpperCase())}
                    required
                    className="w-full px-4 py-3.5 bg-slate-900 border border-slate-800 rounded-xl text-white font-mono text-base tracking-wider uppercase focus:outline-none focus:border-purple-500/60 placeholder:text-slate-600"
                  />
                </div>
              </div>

              <button
                type="submit"
                disabled={submitting || !code.trim()}
                className="w-full py-3.5 rounded-xl bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-500 hover:to-indigo-500 text-white font-bold text-sm tracking-wide shadow-lg shadow-purple-600/25 active:scale-[0.99] transition-all flex items-center justify-center gap-2 cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {submitting ? (
                  <div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin" />
                ) : (
                  <>
                    <Sparkles className="w-4 h-4" />
                    <span>Redeem Code & Credit Balance</span>
                  </>
                )}
              </button>
            </form>
          </div>
        </div>

        {/* Right: My Personal Redemption History */}
        <div className="lg:col-span-6 space-y-6">
          {/* User's Claimed History (shows only codes this user personally redeemed) */}
          <div className="bg-[#0e1628]/90 border border-slate-800 rounded-3xl p-6 sm:p-8">
            <div className="flex items-center justify-between mb-4">
              <h2 className="text-base font-bold text-white flex items-center gap-2">
                <History className="w-4 h-4 text-emerald-400" />
                My Claimed Vouchers
              </h2>
              <span className="text-xs text-slate-400">{myRedemptions.length} Claimed</span>
            </div>

            <div className="space-y-2.5">
              {loadingHistory ? (
                <div className="py-6 text-center text-slate-500 text-xs">
                  Loading redemption history...
                </div>
              ) : myRedemptions.length === 0 ? (
                <div className="py-6 text-center text-slate-500 text-xs">
                  You haven&apos;t claimed any promotional vouchers yet.
                </div>
              ) : (
                myRedemptions.map((item) => (
                  <div
                    key={item.id}
                    className="p-3.5 rounded-xl bg-slate-900/80 border border-slate-800 flex items-center justify-between gap-3 text-xs"
                  >
                    <div className="flex items-center gap-2.5">
                      <div className="w-7 h-7 rounded-lg bg-emerald-500/10 text-emerald-400 flex items-center justify-center shrink-0">
                        <CheckCircle2 className="w-4 h-4" />
                      </div>
                      <div>
                        <span className="font-mono font-bold text-slate-200">
                          {item.promoCode}
                        </span>
                        <p className="text-[11px] text-slate-500">
                          {new Date(item.redeemedAt).toLocaleString()}
                        </p>
                      </div>
                    </div>

                    <span className="px-2.5 py-1 rounded-full font-bold font-mono text-xs bg-emerald-500/15 text-emerald-400 border border-emerald-500/30">
                      +${item.rewardAmount.toFixed(2)}
                    </span>
                  </div>
                ))
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
